package model;
/**
 * 
 * @author Yasas De Silva
 * This class is for Auto Generated Lessons.
 */
public class AGL {
	
	private String aglID="agl_id";	
	private String aglWord="agl_word";		
	private String aglLesson="agl_lesson";
	private String aglFor="agl_for";	
	private String aglForName="(SELECT user_name FROM ssts.users where user_id= autogeneratedlessons.agl_for)";
	private String genOn="gen_on";
	private int minID;
	private int maxID;
	
	
	/**
	 * @return the aglID
	 */
	public String getAglID() {
		return aglID;
	}
	/**
	 * @param aglID the aglID to set
	 */
	public void setAglID(String aglID) {
		this.aglID = aglID;
	}
	/**
	 * @return the aglWord
	 */
	public String getAglWord() {
		return aglWord;
	}
	/**
	 * @param aglWord the aglWord to set
	 */
	public void setAglWord(String aglWord) {
		this.aglWord = aglWord;
	}
	/**
	 * @return the aglLesson
	 */
	public String getAglLesson() {
		return aglLesson;
	}
	/**
	 * @param aglLesson the aglLesson to set
	 */
	public void setAglLesson(String aglLesson) {
		this.aglLesson = aglLesson;
	}
	/**
	 * @return the aglFor
	 */
	public String getAglFor() {
		return aglFor;
	}
	/**
	 * @param aglFor the aglFor to set
	 */
	public void setAglFor(String aglFor) {
		this.aglFor = aglFor;
	}
	/**
	 * @return the aglForName
	 */
	public String getAglForName() {
		return aglForName;
	}
	/**
	 * @param aglForName the aglForName to set
	 */
	public void setAglForName(String aglForName) {
		this.aglForName = aglForName;
	}
	/**
	 * @return the genOn
	 */
	public String getGenOn() {
		return genOn;
	}
	/**
	 * @param genOn the genOn to set
	 */
	public void setGenOn(String genOn) {
		this.genOn = genOn;
	}
	/**
	 * @return the minID
	 */
	public int getMinID() {
		return minID;
	}
	/**
	 * @param minID the minID to set
	 */
	public void setMinID(int minID) {
		this.minID = minID;
	}
	/**
	 * @return the maxID
	 */
	public int getMaxID() {
		return maxID;
	}
	/**
	 * @param maxID the maxID to set
	 */
	public void setMaxID(int maxID) {
		this.maxID = maxID;
	}
	
	
}
